on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: Instala as dependências
          run: npm install

        - name: Executa o lint para verificar se existem erros
          run: npx eslint .
  testes:
      runs-on: ubuntu-latest
      steps:
          - name: Verifica o repositório do Git
            uses: actions/checkout@v2

          - name: Instala o node com a versão
            uses: actions/setup-node@v1
            with:
              node-version: 14

          - name: Instala as dependências
            run: npm install

          - name: Executa todos os testes unitários
            run: npm test

  # Aguarda implementacao de testes para executar esse job
  # tests:
  #     runs-on: ubuntu-latest
  #     env:
  #       MYSQL_USER: root
  #       MYSQL_PASSWORD: password
  #       MYSQL_DATABASE: PDV
  #       MYSQL_PORT: 3306
  #       HOSTNAME: localhost
  #       DIALECT: mysql
  #       SECRET: secret
  #     steps:
  #         - name: Verifica o repositório do Git
  #           uses: actions/checkout@v2

  #         - name: Inicia containers
  #           run: docker-compose up -d

  #         - name: Instala as dependências
  #           run: npm install

  #         - name: Executa Sequelize
  #           run: npm run restore

  #         - name: Executa todos os testes
  #           run: npm test

  #         - name: Para os containers
  #           if: always()
  #           run: docker-compose -f "docker-compose.yml" down