on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
        - name: Verifica o repositório do Git
          uses: actions/checkout@v2

        - name: Instala o node com a versão
          uses: actions/setup-node@v1
          with:
            node-version: 14

        - name: Instala as dependências
          run: npm install

        - name: Executa o lint para verificar se existem erros
          run: npx eslint .
  tests:
      runs-on: ubuntu-latest
      env:
        DB_USER: root
        DB_PASSWORD: password
        DB_DATABASE: PSEL-XP
        DB_HOSTNAME: localhost
        DB_PORT: 3306
        DB_DIALECT: mysql
        SECRET: mySecret
      steps:
          - name: Verifica o repositório do Git
            uses: actions/checkout@v2

          - name: Inicia containers
            run: docker-compose up -d

          - name: Instala as dependências
            run: npm install

          - name: Executa Sequelize
            run: npm run db:restore

          - name: Executa todos os testes
            run: npm test

          - name: Para os containers
            run: docker-compose down